# Generated by Django 4.2.7 on 2023-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isHealthWorker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isResearcher',
            field=models.BooleanField(default=False),
        ),
    ]
