# Generated by Django 4.2.7 on 2023-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_user_ishealthworker_user_isresearcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
