# Generated by Django 4.2.7 on 2023-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_alter_patient_height_alter_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
