# Generated by Django 4.2.7 on 2023-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_alter_patient_firstname_alter_patient_healthhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.CharField(default='2023-01-01', max_length=500),
        ),
    ]
